### ISSUE TITLE
Add  ragg and svglite devices

### ISSUE THREAD

**Issue by z3tt** [thebioengineer/camcorder#15]
The recent updates of the {ragg} and {svglite} packages allow new devices to export plots that hopefully fix all issues related to custom fonts, emoji use etc. Would be great to use this functionality in our package as well.

**Comment by z3tt** [comment]
#17 might be solved once we tackle this?

**Comment by thebioengineer** [comment]
I think that would make sense - might be beneficial to rethink how this is set up to allow users to pass functions as opposed to just "png","pdf"....
