### ISSUE TITLE
RStudio viewer always shows plot by old code

### ISSUE THREAD

**Issue by gkaramanis** [thebioengineer/camcorder#16]
Ok, this is really strange, I don't  know how to reproduce it. I work with this week's TidyTuesday data and made a plot with facets.

I started using camcorder after the first plots and started changing the gglot code. The RStudio viewer shows the faceted plot every single time, no matter what the new code is. The same happens after restarting the R session and even restarting RStudio, I'm really confused!  The exported images contain the correct plot.

**Comment by gkaramanis** [comment]
Update: it seems to be related to the tidytuesday project file I use. It works as expected when I start another instance of RStudio with another project file.

**Comment by z3tt** [comment]
Does this issue still pop up or were you able to fix it by rebuilding the project file? Or can we close this issue?

**Comment by gkaramanis** [comment]
Haven't seen the issue for a long time

**Comment by gkaramanis** [comment]
So. this is happening again, this time when working with a single script, i.e. not a project file. The plot viewer works fine until I attach camcorder and use gg_record, then it always shows a plot made days ago.

It seems that the issue is related to the specific plot made before, here is some more info:
- The plot was saved with tmap_save (not gg_record or ggsave)
- If I use another directory in gg_record, everything works as expected
- Deleting the persistent plot and restarting the R session fixes the issue
- If I put back the file, it happens again
- Renaming the file does not fix the issue

**Comment by thebioengineer** [comment]
Oh no, sorry! if you can send some reproducible code, that would be great so I can see what is going on. It's so weird!

**Comment by gkaramanis** [comment]
I can't reproduce it, sorry... Saved some new plots with tmap_save to see if they would "stick" instead of the old plot, but it's always that same old plot that shows up

It's probably not worth spending time on it since it's so random. I'm happy that I found out that is file specific, I moved the old plot to a subdirectory and it is fixed 😄

**Comment by thebioengineer** [comment]
Sounds good. At some point I'd be curious for us to get on a call and try to sort out what us going on so we can try to prevent it in the future
