### ISSUE TITLE
No output when using geofacet

### ISSUE THREAD

**Issue by gkaramanis** [thebioengineer/camcorder#19]
I get no file when I use facet_geo() in my plots, have tried png, pdf and svg. I can save a plot "manually" with ggsave. I have the following versions installed:

geofacet_0.2.0 
camcorder_0.0.2
ggplot2_3.3.5

Here is the geofacet vignette with some camcorder code. I get no file at all with facet_geo(), if I comment it out, camcorder works as expepted.

``` r
library(ggplot2)
library(camcorder)
library(geofacet)

gg_record(dir = "~/Desktop/temp", device = "png", width = 10, height = 8, units = "in", dpi = 320)

ggplot(state_ranks, aes(variable, rank, fill = variable)) +
  geom_col() +
  coord_flip() +
  facet_geo(~ state) +
  theme_bw()
```

![](https://i.imgur.com/HSPezZg.png)

<sup>Created on 2021-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by thebioengineer** [comment]
Interesting. On investigation, it looks like the output from a `facet_geo` function is a `facet_geo` object (with `gg` and `ggplot` classes as well). To print, it calls `geofacet::print.facet_geo`, and ultimately `grid::grid_draw` under the hood. This means it is not using the print.ggplot or print.patchwork, which is what camcorder overrides to grab the prints. 

``` r
library(ggplot2)
library(camcorder)
library(geofacet)

# gg_record(dir = "~/Desktop/temp", device = "png", width = 10, height = 8, units = "in", dpi = 320)

state_plot <- ggplot(geofacet::state_ranks, aes(variable, rank, fill = variable)) +
  geom_col() +
  coord_flip() +
  facet_geo(~ state) +
  theme_bw()

class(state_plot)
#> [1] "facet_geo" "gg"        "ggplot"
   
geofacet:::print.facet_geo
#> function (x, newpage = is.null(vp), vp = NULL, ...) 
#> {
#>     if (newpage) 
#>         grid::grid.newpage()
#>     g <- get_geofacet_grob(x)
#>     grid::grid.draw(g)
#> }
#> <bytecode: 0x000000002c90ba88>
#> <environment: namespace:geofacet>
```

<sup>Created on 2021-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by thebioengineer** [comment]
This brings up how do we expand camcorder to deal with additional plotting devices. One option is to get into the lower level "how does R print stuff", which may be an interesting exercise, but not one I have much time for at the moment.

**Comment by gkaramanis** [comment]
Interesting, thanks for the explanation! I was mostly wondering if the new ggplot version broke something but I probably hadn't used geofacet with camcorder before

**Comment by thebioengineer** [comment]
so...ive been mulling this over and I think I may have an idea. To handle cases where we havent come up with a method/it wouldnt be simple to create one,  we could provide a function `record_plot()` that you add at the end. I know its relatively similar to how you and @z3tt used to do saves, but it would still use the functionality of camcorder. 

so your code would look like:

```r
library(ggplot2)
library(camcorder)
library(geofacet)

gg_record(dir = "~/Desktop/temp", device = "png", width = 10, height = 8, units = "in", dpi = 320)

ggplot(state_ranks, aes(variable, rank, fill = variable)) +
  geom_col() +
  coord_flip() +
  facet_geo(~ state) +
  theme_bw() 

record_polaroid()

gg_stop_recording()



```

**Comment by gkaramanis** [comment]
That would be nice to have! Much easier to add record_polaroid() when we already have camcorder set up :)

**Comment by thebioengineer** [comment]
Awesome. I have code in the `polaroid` branch right now if you want to take it for a test ride.

**Comment by gkaramanis** [comment]
Sure! I can't seem to install any of the branches though. I see `dev` and `recording_tests`, I get `Error: object ‘win.metafile’ is not exported by 'namespace:grDevices'` with both

**Comment by thebioengineer** [comment]
oh, my bad. I merged polaroid into dev last night without thinking! 

I'll need to look into that, I've not seen that error before. Could you share your session info? or is this when you try to install those branches?

**Comment by gkaramanis** [comment]
No worries! I get the error message when I was trying to install the branches

**Comment by gkaramanis** [comment]
`record_polaroid()` from the `recording-tests` branch works with `facet_geo()`!
 It even saves base R plots and plots from other packages (only tested UpSetR), excellent! 😁

**Comment by thebioengineer** [comment]
Awesome! Good to hear you like it. This is what I mean by sorting out the more in depth behavior of R's graphic devices. Unfortunately I don't think we can override them to generically capture anything printed to them

**Comment by z3tt** [comment]
So we can merge it and are all set here?
