### ISSUE TITLE
Hex logo

### ISSUE THREAD

**Issue by gkaramanis** [thebioengineer/camcorder#2]
I made a quick logo, do you like the concept or should we do something else?

**Comment by Z3tt** [comment]
I love it! What does the black triangle on the right represent? Is it a play button?

Related name discussion: `camcordr` would be an option as well, what do you think? I like both `camcorder` and `camcordr`

**Comment by gkaramanis** [comment]
The triangle is the tape that is inside the VHS box. Not so obvious, I guess 🙃

Both names work for me!

**Comment by thebioengineer** [comment]
I'm loving the hex - much more creative and digging the retro nod. we could lean into that if you want to change it, otherwise I'm happy!

Also, unless you feel strongly, I feel like `camcorder` might be a little easier to remember 🤷

**Comment by Z3tt** [comment]
Let's stick to `camcorder` as package name. 
So I am going to close that issue since we all ❤️ the logo. Thanks @gkaramanis!
