### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Pablo-Alvarez-Baeza** [thebioengineer/camcorder#20]
I'm trying to install the package but I receive the following error message. Is there a package missing I need to install?

Thanks in advance,

> remotes::install_github("thebioengineer/camcorder")

Downloading GitHub repo thebioengineer/camcorder@HEAD
✔  checking for file ‘/private/var/folders/zy/mb83lfs57_q86yc8h2zgq5c80000gn/T/Rtmp24STDm/remotes42165afa29a0/thebioengineer-camcorder-68867a1/DESCRIPTION’ ...
─  preparing ‘camcorder’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘camcorder/inst/gif_samples’
   Removed empty directory ‘camcorder/inst’
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘camcorder_0.0.2.9000.tar.gz’
   
* installing *source* package ‘camcorder’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/pdftools/libs/pdftools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/pdftools/libs/pdftools.so, 0x0006): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.2/Resources/library/pdftools/libs/pdftools.so
  Reason: tried: '/opt/X11/lib/libXrender.1.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libXrender.1.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/server/libXrender.1.dylib' (no such file)
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘camcorder’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/camcorder’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/zy/mb83lfs57_q86yc8h2zgq5c80000gn/T//Rtmp24STDm/file42165dc2f609/camcorder_0.0.2.9000.tar.gz’ had non-zero exit status

**Comment by Pablo-Alvarez-Baeza** [comment]
I had to install XQuartz on Mac (https://www.xquartz.org) and then I was able to install it.

**Comment by z3tt** [comment]
Thanks @Pablo-Alvarez-Baeza, we will add that information to the installation notes.
