### ISSUE TITLE
`bg` argument to set non-transparent backgrounds

### ISSUE THREAD

**Issue by z3tt** [thebioengineer/camcorder#30]
While re-rendering the vignette gif I noticed that pngs are saved with a trasnparent background, as now common with the ragg devices. It would be great to have a bg option as in those or (maybe keeping it more simple but not sure if easy to implement) to set the backround white in case it is transparent and leave it as it is otherwise.

**Comment by thebioengineer** [comment]
Hmmm, that's so weird. We could add that option to gg_record if it isn't there, I think we do set background for the saving of the gif

**Comment by z3tt** [comment]
I just saw there is a `background` argument in `gg_playback()`. However, backgrounds are always black for me anyway. IMO would be better to set it for the saved plots themselves. First, one may want to use the static plots as well. Secondly, one could still have a background of different color in case image sizes switch within an animation.

**Comment by z3tt** [comment]
Btw, I was able to create a gif without a plot or panel background again (different Win machine, same camcorder version).
![diamonds](https://user-images.githubusercontent.com/7523556/186136999-440c869f-ce58-4347-8216-fe24fb980476.gif)

**Comment by thebioengineer** [comment]
corrected in #36
