### ISSUE TITLE
Pixels in units?

### ISSUE THREAD

**Issue by gkaramanis** [thebioengineer/camcorder#35]
Just a little thing I noticed today when I tried to set the plot size in pixels. The popup says that it can be "px", I don't know if this comes from camcorder or somewhere else. I almost never use pixels, it would be nice to add if possible,  it was mostly the inconsistency that confused me there for a moment 😄 

<img width="1547" alt="Screenshot 2022-09-21 at 05 12 25" src="https://user-images.githubusercontent.com/3393168/191417292-3c17e738-6c89-4d62-b848-462dcd75b1da.png">

**Comment by thebioengineer** [comment]
addressed in #36 - will merge in to dev once it passes CI, then dev into main
